name: Java Main Methods CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compile Java files
      run: |
        find . -name "*.java" > sources.txt
        javac @sources.txt

    - name: Run all main() classes
      run: |
        find . -name "*.java" | while read file; do
          classname=$(echo $file | sed 's|./||; s|/|.|g; s|.java$||')
          echo "Running $classname"
          timeout 10s java $classname || { echo "$classname failed"; exit 1; }
        done
